export default [
        {
          "_class": "com.glt.ptwiki.leads.dto.Question",
          "id": 1,
          "clinicId" : 1,
          "clinicLocationId": 1,
          "clinicLocationServiceId": 1,
          "questionDescription": "On a scale of 1-10, one being hardly any pain and ten being excruciating, how would you rate your pain?",
          "isMandatory" : true,
          "isActive": true,
          "answerType": "dropdown",
          "orderNumber": 1,
          "multipleSelectAllowed" : false,
          "optionsDescription": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
        },
        {
          "_class": "com.glt.ptwiki.leads.dto.Question",
          "id": 2,
          "clinicId" : 1,
          "clinicLocationId": 1,
          "clinicLocationServiceId": 1,
          "questionDescription": "How did the pain begin?",
          "isMandatory" : true,
          "isActive": true,
          "answerType": "dropdown",
          "orderNumber": 2,
          "multipleSelectAllowed" : false,
          "optionsDescription": ["Accident at home", "Vehicle accident", " Accident at work/ work related", "It just began", "After surgery", "Came on gradually", "Sports related", "Other"]
        },
        {
          "_class": "com.glt.ptwiki.leads.dto.Question",
          "id": 3,
          "clinicId" : 1,
          "clinicLocationId": 1,
          "clinicLocationServiceId": 1,
          "questionDescription": "What type of doctors or specialists have seen?",
          "isMandatory" : true,
          "isActive": true,
          "answerType": "checkbox",
          "orderNumber": 3,
          "multipleSelectAllowed" : true,
          "optionsDescription": ["Physical Therapist", "Chiropractor", "Pain Management", "Neurologist", "Orthopaedic Surgeon", "General/ Family Doctor", "Other", "None"]
        },
        {
          "_class": "com.glt.ptwiki.leads.dto.Question",
          "id": 4,
          "clinicId" : 1,
          "clinicLocationId": 1,
          "clinicLocationServiceId": 1,
          "questionDescription": "How committed are you to fixing your pain?",
          "isMandatory" : true,
          "isActive": true,
          "answerType": "dropdown",
          "orderNumber": 4,
          "multipleSelectAllowed" : false,
          "optionsDescription": ["Very committed", "Somewhat committed", "Neutral", "Not ready to commit yet"]
        },
        {
          "_class": "com.glt.ptwiki.leads.dto.Question",
          "id": 5,
          "clinicId" : 1,
          "clinicLocationId": 1,
          "clinicLocationServiceId": 1,
          "questionDescription": "What Medical insurance (if any) do you have?",
          "isMandatory" : false,
          "isActive": true,
          "answerType": "text",
          "orderNumber": 5,
          "multipleSelectAllowed" : false
        },
        {
          "_class": "com.glt.ptwiki.leads.dto.Question",
          "id": 6,
          "clinicId" : 1,
          "clinicLocationId": 1,
          "clinicLocationServiceId": 1,
          "questionDescription": "When did you last visit your doctor?",
          "isMandatory" : true,
          "isActive": true,
          "answerType": "radio",
          "orderNumber": 6,
          "multipleSelectAllowed" : false,
          "optionsDescription": ["Within last week", "Within last month", "Within last year", "Older than a year"]
        },
      ]